# Generated by Django 4.1.1 on 2022-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_user_home_user_photo_trip_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
