# Generated by Django 4.1.1 on 2022-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_trip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='img',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
