# Generated by Django 4.1.1 on 2022-12-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_trip_title_alter_trip_img_alter_trip_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list',
            new_name='lists',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tags',
        ),
    ]
