# Generated by Django 4.1.1 on 2022-12-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_rename_list_list_lists_rename_tag_tag_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profpic',
            field=models.ImageField(default='/media/defaultprofpic.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='img',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
