# Generated by Django 4.1.1 on 2022-12-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_user_profpic_alter_trip_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='future', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
