# Generated by Django 4.1.1 on 2022-12-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_trip_status_alter_trip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='media')),
                ('trips', models.ManyToManyField(blank=True, related_name='tripPhotos', to='travel.trip')),
            ],
        ),
    ]
