# Generated by Django 4.1.1 on 2022-12-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_photo_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='trips',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='travel.trip'),
        ),
    ]
