# Generated by Django 4.1.1 on 2022-12-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_photo_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='trips',
        ),
    ]
