# Generated by Django 4.1.1 on 2022-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_photo_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='trips',
        ),
        migrations.AddField(
            model_name='photo',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='tripPhotos', to='travel.trip'),
        ),
    ]
