# Generated by Django 4.1.1 on 2022-12-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_remove_photo_trips_photo_trips'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
