# Generated by Django 4.1.1 on 2022-12-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='media')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='travel.trip')),
            ],
        ),
    ]
