# Generated by Django 4.1.1 on 2022-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
